---
volumes:
  pgadmin:

services:
  pgadmin-compose:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@provider.com
      PGADMIN_DEFAULT_PASSWORD: Admin@123
    ports:
      - '16543:80'
    volumes:
       - pgadmin:/var/lib/pgadmin

networks:
  default:
    name: your_app_default
